name: shared-ci

on:
  workflow_call:

jobs:
  rollout:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate.outputs.result }}
    steps:
      - name: generate
        id: generate
        run: echo "result=1" >> $GITHUB_OUTPUT

  dispatchEvent:
    runs-on: ubuntu-latest
    needs: rollout
    env:
      WORKFLOW: dynamic-workflow-${{ needs.rollout.outputs.version }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: run
        run: gh workflow run $WORKFLOW
  
  generate:
    needs: rollout
    runs-on: ubuntu-latest
    steps:
      - name: generate-workflow
        id: generate
        run: |
          ls -altr /home/runner/work
          ls -altr /home/runner/actions-runner
          # find / -name "*.yml"
          # find / -name "*.yaml"
          pwd
          cat <<'EOF' >> ./.github/workflows/dynamic-workflow.yml
                - name: hello-world
                  run: echo "Hello World"
          EOF

  dw:
    needs: generate
    uses: ./.github/workflows/dynamic-workflow.yml

  dw1:
    needs: rollout
    if: ${{ needs.rollout.outputs.version == 1 }}
    uses: harvey1327/shared-workflows/.github/workflows/dynamic-workflow-1.yml@main
  
  dw2:
    needs: rollout
    if: ${{ needs.rollout.outputs.version == 2 }}
    uses: harvey1327/shared-workflows/.github/workflows/dynamic-workflow-1.yml@main

  # dwv:
  #   needs: rollout
  #   uses: harvey1327/shared-workflows/.github/workflows/dynamic-workflow-${{ needs.rollout.outputs.version }}.yml@main
